### ISSUE TITLE
Isolation interference error

### ISSUE THREAD

**Issue by pwilmart** [kevinkovalchik/RawQuant#17]
Hi Kevin,
I am playing with the triple KO yeast data from the Gygi lab. The Lumos runs (SPS MS3 and MS2) process fine with the -i option. The Fusion files give an error (below).
Cheers,
Phil

(base) E:\PXD008009_TripleKNO\raw_files>python -m RawQuant quant -r TMT11 -i -f m06677.raw

File(s) to be processed:
m06677.raw

Opening m06677.raw and initializing

Data file: m06677.raw
Instrument: Orbitrap Fusion
Experiment MS order: 3

m06677.raw: Extracting MS2TrailerExtra
100%|███████████████████████████| 6335/6335 [00:00<00:00, 7366.92it/s]
m06677.raw: Extracting precursor masses
m06677.raw: Extracting precursor scan numbers
m06677.raw: Extracting MS1TrailerExtra
100%|███████████████████████████| 1362/1362 [00:00<00:00, 7242.38it/s]
m06677.raw: Extracting MS3TrailerExtra
100%|███████████████████████████| 6335/6335 [00:00<00:00, 7654.98it/s]
m06677.raw:Extracting precursor charges
m06677.raw: Extracting MS1LabelData
100%|███████████████████████████| 1362/1362 [00:01<00:00, 1117.80it/s]
m06677.raw: Quantifying MS1 interference: centroid data
  0%|                                        | 0/6335 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "C:\Users\pwilmart\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\pwilmart\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\pwilmart\Anaconda3\lib\site-packages\RawQuant\__main__.py", line 833, in <module>
    data.QuantifyInterference()
  File "C:\Users\pwilmart\Anaconda3\lib\site-packages\RawQuant\RawQuant.py", line 537, in QuantifyInterference
    precIntensities = [pepIntensity[0]]
IndexError: index 0 is out of bounds for axis 0 with size 0
Closing m06677.raw

**Comment by kevinkovalchik** [comment]
Hi Phil,
Thanks for bringing it up. I'm working on a deadline right now, but I'll get to this (and the other issue you raised!) when I get a chance. Probably sometime next week.
Kevin
